sqlite3 eBay.db < create.sql
sqlite3 eBay.db < trigger8_add.sql
sqlite3 eBay.db < trigger9_add.sql
sqlite3 eBay.db < trigger11_add.sql
sqlite3 eBay.db < trigger12_add.sql
sqlite3 eBay.db < trigger13_add.sql
sqlite3 eBay.db < trigger14_add.sql
sqlite3 eBay.db < trigger15_add.sql
sqlite3 eBay.db < trigger16_add.sql
sqlite3 eBay.db < load.txt
sqlite3 eBay.db < constraints_verify.sql